spring.application.name=spring-profiling
server.port=5001


spring.profiles.active=staging,prod

#prod.db.url=jdbc:mysql://x:y/food
#staging.db.url=jdbc:mysql://a:b/food

spring.datasource.url=jdbc:mysql://x:y/food
food.cuisineName=italian
food.cuisineDescription=Italian_Pasta

#food={cuisineName=italian,cuisineDescription=Italian_Pasta}