package com.example.dependency_injection;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class VehicleService {

    private Engine engine;
    private Wheel wheel;

//    public VehicleService(Engine engine, Wheel wheel) {
//        this.engine = engine;
//        this.wheel = wheel;
//    }

    public Engine getEngine() {
        return engine;
    }

    // This is going to inject the engine dependency which is generated by spring boot during the application startup
    @Autowired
    public void setEngine(Engine engine) {
        System.out.println("Setting the engine to " + engine + " in vehicle service class..");
        this.engine = engine;
    }

    public Wheel getWheel() {
        return wheel;
    }

    @Autowired
    public void setWheel(Wheel wheel1) {
        System.out.println("Setting the wheels to " + wheel + " in vehicle service class..");
        wheel = wheel1;
    }
}
