spring.application.name=demo-jpa

spring.datasource.url=jdbc:mysql://localhost:3306/employees_92
spring.datasource.username=root
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update